- name: creating catalogue
  hosts: catalogue
  become: yes
  tasks: 
  - name: disable old nodejs & enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y 

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present  

  - name: create user
    ansible.builtin.user: 
      name: roboshop 

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: downloading catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: unzip the catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app     
           
